// Every event can be acted on or left alone.
// `effect` describes what ACTING does compared to letting it pass:
//   "same"   - the outcome is identical either way; you only spent yourself
//   "worse"  - intervening actively made it worse
//   "better" - intervening genuinely helped
//
// `loud` events announce themselves as urgent. Loud things almost never need
// you. The quiet ones sometimes do. That asymmetry is the whole game.

export const EVENTS = [
  // ---------------------------------------------------------------- tier 1
  {
    id: "argument",
    tier: 1,
    loud: true,
    text: "Someone is wrong, publicly, and you can prove it.",
    actLabel: "Correct them",
    window: 9,
    cost: 16,
    effect: "same",
    onAct: "You wrote for eleven minutes. They did not change their mind.",
    onPass: "The thread scrolled away. They did not change their mind.",
  },
  {
    id: "kettle",
    tier: 1,
    loud: true,
    text: "The kettle is screaming in the next room.",
    actLabel: "Go turn it off",
    window: 7,
    cost: 9,
    effect: "same",
    onAct: "You got up. It was already clicking off as you reached it.",
    onPass: "It clicked off by itself. Kettles are built to.",
  },
  {
    id: "moth",
    tier: 1,
    loud: false,
    text: "A moth is circling the lamp.",
    actLabel: "Catch it",
    window: 10,
    cost: 7,
    effect: "same",
    onAct: "You chased it around the room. It left through the window.",
    onPass: "It left through the window.",
  },
  {
    id: "cc-email",
    tier: 1,
    loud: true,
    text: "An email marked URGENT. You are only cc'd.",
    actLabel: "Reply all",
    window: 8,
    cost: 18,
    effect: "worse",
    onAct: "You are now the owner of a problem that was not yours.",
    onPass: "Someone whose job it was handled it before lunch.",
  },
  {
    id: "plant",
    tier: 1,
    loud: false,
    text: "The plant on the sill is drooping a little.",
    actLabel: "Water it",
    window: 12,
    cost: 6,
    effect: "better",
    onAct: "By evening it had lifted its leaves again.",
    onPass: "It survived. It did not thrive.",
  },
  {
    id: "music",
    tier: 1,
    loud: true,
    text: "Your neighbour's music is too loud again.",
    actLabel: "Knock on the wall",
    window: 9,
    cost: 14,
    effect: "worse",
    onAct: "Now it is loud and pointed. You have a nemesis on the other side of the plaster.",
    onPass: "It stopped at eleven, the way it always does.",
  },
  {
    id: "meeting",
    tier: 1,
    loud: true,
    text: "Two colleagues are disagreeing, loudly, about something small.",
    actLabel: "Weigh in",
    window: 8,
    cost: 13,
    effect: "same",
    onAct: "They reached the compromise they were already reaching.",
    onPass: "They reached a compromise.",
  },
  {
    id: "mispronounce",
    tier: 1,
    loud: false,
    text: "They mispronounced a word you happen to know.",
    actLabel: "Correct it",
    window: 6,
    cost: 8,
    effect: "worse",
    onAct: "They stopped talking freely around you after that.",
    onPass: "They finished a story that was worth hearing.",
  },
  {
    id: "text-back",
    tier: 1,
    loud: false,
    text: "A friend went quiet three weeks ago.",
    actLabel: "Reach out",
    window: 13,
    cost: 8,
    effect: "better",
    onAct: "They had been waiting for someone to go first. It was you.",
    onPass: "The quiet stretched into a year, and then into a habit.",
  },
  {
    id: "door",
    tier: 1,
    loud: false,
    text: "A door somewhere in the house is slightly open.",
    actLabel: "Go close it",
    window: 11,
    cost: 5,
    effect: "same",
    onAct: "You closed it. The house was exactly as safe as before.",
    onPass: "Nothing came through it.",
  },

  // ---------------------------------------------------------------- tier 2
  {
    id: "rival",
    tier: 2,
    loud: true,
    text: "Someone you quietly measure yourself against just announced good news.",
    actLabel: "Respond to it",
    window: 9,
    cost: 22,
    effect: "worse",
    onAct: "You spent the afternoon comparing two lives that were never the same shape.",
    onPass: "It was good news. It stayed good news, over there, where it happened.",
  },
  {
    id: "rumour",
    tier: 2,
    loud: true,
    text: "A version of you is circulating that isn't accurate.",
    actLabel: "Set the record straight",
    window: 10,
    cost: 24,
    effect: "worse",
    onAct: "Your denial travelled further than the rumour ever would have.",
    onPass: "It died the way rumours die: of boredom.",
  },
  {
    id: "pause",
    tier: 2,
    loud: false,
    text: "The conversation has gone quiet. Nobody is filling it.",
    actLabel: "Fill the silence",
    window: 7,
    cost: 10,
    effect: "same",
    onAct: "You said something. It was fine. Nobody remembered it.",
    onPass: "The silence turned out to be the good part.",
  },
  {
    id: "junior",
    tier: 2,
    loud: false,
    text: "Someone newer than you is struggling and hasn't asked.",
    actLabel: "Offer help",
    window: 12,
    cost: 11,
    effect: "better",
    onAct: "It cost you an hour. It saved them a month.",
    onPass: "They worked it out eventually, alone, and more slowly than they needed to.",
  },
  {
    id: "family-chat",
    tier: 2,
    loud: true,
    text: "The family group chat has become a debate at 11pm.",
    actLabel: "Say your piece",
    window: 8,
    cost: 20,
    effect: "worse",
    onAct: "Two people stopped speaking. One of them was you.",
    onPass: "By morning it had turned back into photographs of a dog.",
  },
  {
    id: "advice",
    tier: 2,
    loud: true,
    text: "You are being given advice you did not ask for and do not need.",
    actLabel: "Push back",
    window: 8,
    cost: 15,
    effect: "same",
    onAct: "They repeated the advice, more slowly.",
    onPass: "They finished, felt useful, and moved on.",
  },
  {
    id: "2am-idea",
    tier: 2,
    loud: true,
    text: "A brilliant idea has arrived. It is 2am.",
    actLabel: "Act on it now",
    window: 9,
    cost: 21,
    effect: "worse",
    onAct: "You sent the message. You read it again at nine and felt the floor tilt.",
    onPass: "In daylight it was an ordinary idea, and you kept the good half.",
  },
  {
    id: "grudge",
    tier: 2,
    loud: false,
    text: "You are still holding something from four years ago.",
    actLabel: "Put it down",
    window: 14,
    cost: 12,
    effect: "better",
    onAct: "Your hands were free for the first time in a while.",
    onPass: "You carried it into another year. It did not get lighter.",
  },
  {
    id: "bench",
    tier: 2,
    loud: false,
    text: "A stranger on the next bench is crying, quietly.",
    actLabel: "Sit nearer",
    window: 11,
    cost: 10,
    effect: "better",
    onAct: "You said nothing useful. Saying nothing, nearby, was the useful part.",
    onPass: "They cried alone, which people can do, but shouldn't have to.",
  },
  {
    id: "regret",
    tier: 2,
    loud: false,
    text: "An old regret has surfaced without being invited.",
    actLabel: "Examine it again",
    window: 12,
    cost: 16,
    effect: "same",
    onAct: "You turned it over for an hour. It was the same shape as last time.",
    onPass: "It surfaced, drifted, and went back under.",
  },

  // ---------------------------------------------------------------- tier 3
  {
    id: "explain",
    tier: 3,
    loud: true,
    text: "You have been misunderstood, and you could explain yourself completely.",
    actLabel: "Explain",
    window: 10,
    cost: 26,
    effect: "worse",
    onAct: "The explanation became the thing they remembered instead.",
    onPass: "You were misunderstood. You went on being who you actually were.",
  },
  {
    id: "news",
    tier: 3,
    loud: true,
    text: "Something enormous is happening, far away, and you can watch all of it.",
    actLabel: "Follow it closely",
    window: 11,
    cost: 28,
    effect: "same",
    onAct: "You knew every detail. Not one of them was yours to change.",
    onPass: "It happened. You learned of it later, and did the one thing you could.",
  },
  {
    id: "body",
    tier: 3,
    loud: false,
    text: "Your body has been sending the same small signal for months.",
    actLabel: "Finally see someone",
    window: 15,
    cost: 14,
    effect: "better",
    onAct: "It was early. Early is the whole thing.",
    onPass: "It kept signalling, patiently, and then it stopped being small.",
  },
  {
    id: "fix-someone",
    tier: 3,
    loud: true,
    text: "You can see exactly what someone else should do with their life.",
    actLabel: "Tell them",
    window: 9,
    cost: 25,
    effect: "worse",
    onAct: "They did it, badly, and it was your fault instead of their choice.",
    onPass: "They found a worse route to a better place, and it belonged to them.",
  },
  {
    id: "deferred",
    tier: 3,
    loud: false,
    text: "The thing you keep meaning to start is still not started.",
    actLabel: "Begin badly",
    window: 16,
    cost: 15,
    effect: "better",
    onAct: "The first version was poor. It existed. That was the hard part.",
    onPass: "It stayed perfect and unmade, which is the safest way to lose something.",
  },
  {
    id: "apology",
    tier: 3,
    loud: false,
    text: "There is an apology you owe and have not made.",
    actLabel: "Make it",
    window: 14,
    cost: 13,
    effect: "better",
    onAct: "It was less painful than the eleven years of not doing it.",
    onPass: "You rehearsed it for another year and delivered it to nobody.",
  },
  {
    id: "career",
    tier: 3,
    loud: true,
    text: "A door is closing on a path you spent a decade on.",
    actLabel: "Jam it open",
    window: 12,
    cost: 30,
    effect: "same",
    onAct: "It closed anyway, and your hand was in it.",
    onPass: "It closed. The corridor turned out to have other doors.",
  },
  {
    id: "grief",
    tier: 3,
    loud: false,
    text: "Grief has arrived and is sitting down across from you.",
    actLabel: "Do something about it",
    window: 15,
    cost: 22,
    effect: "same",
    onAct: "You kept very busy. It waited, without impatience, until you stopped.",
    onPass: "It stayed a while. It moved through you. It did not need managing.",
  },
];

export function bestChoice(event) {
  return event.effect === "better" ? "act" : "pass";
}

export function eventsForTier(tier, catalog = EVENTS) {
  return catalog.filter((e) => e.tier <= tier);
}

export function pickEvent(tier, random = Math.random, recentIds = [], catalog = EVENTS) {
  const pool = eventsForTier(tier, catalog);
  const fresh = pool.filter((e) => !recentIds.includes(e.id));
  const source = fresh.length ? fresh : pool;
  return source[Math.floor(random() * source.length) % source.length];
}

export function resolveEvent(event, acted) {
  const right = bestChoice(event) === (acted ? "act" : "pass");
  return {
    id: event.id,
    acted,
    right,
    changedAnything: acted && event.effect !== "same",
    madeWorse: acted && event.effect === "worse",
    helped: acted && event.effect === "better",
    missed: !acted && event.effect === "better",
    text: acted ? event.onAct : event.onPass,
    cost: acted ? event.cost : 0,
  };
}
