// Crops database
export const CROPS = {
  parsnip: {
    id: "parsnip",
    name: "Parsnip",
    growTime: 6, // seconds in day
    yieldValue: 8,
    xp: 6,
    seedCost: 4,
    color: "#fffae0",
    leafColor: "#55a840",
    icon: "🥕",
    unlockedAtDay: 1,
  },
  potato: {
    id: "potato",
    name: "Sturdy Potato",
    growTime: 9,
    yieldValue: 18,
    xp: 14,
    seedCost: 9,
    color: "#c99e65",
    leafColor: "#3e8c32",
    icon: "🥔",
    unlockedAtDay: 1,
  },
  strawberry: {
    id: "strawberry",
    name: "Blood Strawberry",
    growTime: 14,
    yieldValue: 40,
    xp: 30,
    seedCost: 20,
    color: "#ff3b56",
    leafColor: "#22772e",
    icon: "🍓",
    unlockedAtDay: 2,
  },
  cauliflower: {
    id: "cauliflower",
    name: "Iron Cauliflower",
    growTime: 20,
    yieldValue: 90,
    xp: 65,
    seedCost: 45,
    color: "#e8f5e9",
    leafColor: "#1b5e20",
    icon: "🥦",
    unlockedAtDay: 3,
  },
  starfruit: {
    id: "starfruit",
    name: "Astral Starfruit",
    growTime: 30,
    yieldValue: 240,
    xp: 180,
    seedCost: 110,
    color: "#ffd700",
    leafColor: "#00e676",
    icon: "⭐",
    unlockedAtDay: 5,
  },
};

// Weapons & Boons (Vampire Survivors style automatic weapons & passives)
export const WEAPONS = {
  scythe: {
    id: "scythe",
    name: "Reaper Scythe",
    type: "weapon",
    desc: "Swings a sharp crescent blade around you, cleaving hordes.",
    maxLevel: 5,
    icon: "🌾",
    cooldown: 1.1,
    damage: 18,
    range: 75,
    duration: 0.25,
    knockback: 65,
    evolutionReq: "fertilizer",
    evolutionName: "Soul Harvester",
    evolutionDesc: "Massive twin scythes that heal 1 HP on kill.",
  },
  sprinkler: {
    id: "sprinkler",
    name: "Pressure Sprinkler",
    type: "weapon",
    desc: "Shoots rotating high-pressure water jets that pierce enemies and water nearby crops.",
    maxLevel: 5,
    icon: "💦",
    cooldown: 0.8,
    damage: 12,
    speed: 260,
    pierce: 3,
    evolutionReq: "wateringCan",
    evolutionName: "Tsunami Matrix",
    evolutionDesc: "Torrential 8-way streams that drown elite foes.",
  },
  scarecrow: {
    id: "scarecrow",
    name: "Haunted Scarecrow",
    type: "weapon",
    desc: "Summons floating scarecrows that orbit and electrocute encroaching pests.",
    maxLevel: 5,
    icon: "🎃",
    cooldown: 2.5,
    damage: 15,
    count: 2,
    orbitRadius: 90,
    evolutionReq: "hayBale",
    evolutionName: "Wicker Golem",
    evolutionDesc: "Giant burning scarecrow radiating continuous solar fire.",
  },
  pitchfork: {
    id: "pitchfork",
    name: "Iron Pitchfork",
    type: "weapon",
    desc: "Hurls heavy pitchforks in the direction you are facing.",
    maxLevel: 5,
    icon: "🔱",
    cooldown: 0.95,
    damage: 28,
    speed: 340,
    knockback: 110,
    evolutionReq: "boots",
    evolutionName: "Titan Trident",
    evolutionDesc: "Triple exploding spears that shred enemy armor.",
  },
  beehive: {
    id: "beehive",
    name: "Queen Bee Hive",
    type: "weapon",
    desc: "Unleashes swarms of angry bees that seek out the nearest monsters.",
    maxLevel: 5,
    icon: "🐝",
    cooldown: 1.6,
    damage: 10,
    count: 4,
    speed: 210,
    evolutionReq: "honeyComb",
    evolutionName: "Apis Swarm Sovereign",
    evolutionDesc: "Constant storm of venomous golden hornets.",
  },
  sunburst: {
    id: "sunburst",
    name: "Solar Totem",
    type: "weapon",
    desc: "Drops searing sunbeams from the sky onto cluster of foes.",
    maxLevel: 5,
    icon: "☀️",
    cooldown: 2.0,
    damage: 35,
    radius: 60,
    evolutionReq: "clover",
    evolutionName: "Supernova Beacon",
    evolutionDesc: "Massive orbital laser strikes burning ground in place.",
  },
};

// Passives / Accessories
export const PASSIVES = {
  fertilizer: {
    id: "fertilizer",
    name: "Enriched Compost",
    type: "passive",
    desc: "+15% Damage & +15% Crop growth speed per level.",
    maxLevel: 5,
    icon: "💩",
    stat: "damageMult",
    valuePerLevel: 0.15,
  },
  wateringCan: {
    id: "wateringCan",
    name: "Copper Watering Can",
    type: "passive",
    desc: "-10% Attack Cooldown & auto-waters adjacent tilled soil.",
    maxLevel: 5,
    icon: "🫖",
    stat: "cooldownMult",
    valuePerLevel: 0.1,
  },
  hayBale: {
    id: "hayBale",
    name: "Dense Haystack",
    type: "passive",
    desc: "+20 Max HP & +0.5 HP/sec natural regeneration.",
    maxLevel: 5,
    icon: "🌾",
    stat: "maxHp",
    valuePerLevel: 20,
  },
  boots: {
    id: "boots",
    name: "Rubber Wellies",
    type: "passive",
    desc: "+12% Movement Speed & trample small obstacles.",
    maxLevel: 5,
    icon: "👢",
    stat: "speedMult",
    valuePerLevel: 0.12,
  },
  honeyComb: {
    id: "honeyComb",
    name: "Golden Honeycomb",
    type: "passive",
    desc: "+25% XP orb collection magnet radius.",
    maxLevel: 5,
    icon: "🍯",
    stat: "magnetRadius",
    valuePerLevel: 35,
  },
  clover: {
    id: "clover",
    name: "Four-Leaf Clover",
    type: "passive",
    desc: "+15% Luck (Crit chance, multi-harvest chance, rare chest rate).",
    maxLevel: 5,
    icon: "🍀",
    stat: "luck",
    valuePerLevel: 0.15,
  },
};

// Evolution recipes checking
export function checkEvolution(weaponId, weaponLevel, inventory) {
  const w = WEAPONS[weaponId];
  if (!w || weaponLevel < w.maxLevel) return false;
  const reqPassive = w.evolutionReq;
  return Boolean(inventory.passives[reqPassive] && inventory.passives[reqPassive] >= 1);
}

// Meta Upgrades (Persistent across runs via Gold earned from shipping crops)
export const META_UPGRADES = [
  {
    id: "startingGold",
    name: "Inherited Wealth",
    desc: "Start each run with bonus +50 Gold.",
    max: 5,
    cost: (lvl) => 100 + lvl * 150,
    icon: "💰",
  },
  {
    id: "plotCount",
    name: "Land Deed Expansion",
    desc: "Unlock +4 extra farm tilled plots on your farm.",
    max: 4,
    cost: (lvl) => 250 + lvl * 300,
    icon: "📜",
  },
  {
    id: "tractor",
    name: "Greenhouse Engine",
    desc: "+20% global crop growth speed in all seasons.",
    max: 5,
    cost: (lvl) => 150 + lvl * 200,
    icon: "🚜",
  },
  {
    id: "vitality",
    name: "Farmstead Vitality",
    desc: "+25 Base Player Max HP.",
    max: 5,
    cost: (lvl) => 80 + lvl * 120,
    icon: "❤️",
  },
  {
    id: "scarecrowBuff",
    name: "Blessed Soil",
    desc: "Crops occasionally drop Healing Hearts or Golden Seeds when harvested.",
    max: 3,
    cost: (lvl) => 300 + lvl * 350,
    icon: "✨",
  },
];

// Monster Types
export const MONSTERS = {
  crow: {
    id: "crow",
    name: "Night Crow",
    hp: 16,
    speed: 75,
    damage: 10,
    size: 14,
    color: "#23202e",
    eyeColor: "#ff3344",
    xp: 2,
    behavior: "flock",
  },
  mole: {
    id: "mole",
    name: "Crop Devourer Mole",
    hp: 35,
    speed: 55,
    damage: 15,
    size: 18,
    color: "#5c4033",
    eyeColor: "#ffff00",
    xp: 4,
    behavior: "burrow",
  },
  bat: {
    id: "bat",
    name: "Cave Bat",
    hp: 22,
    speed: 100,
    damage: 12,
    size: 13,
    color: "#4a154b",
    eyeColor: "#00ffff",
    xp: 3,
    behavior: "swoop",
  },
  weedMonster: {
    id: "weedMonster",
    name: "Cursed Tangleweed",
    hp: 80,
    speed: 38,
    damage: 22,
    size: 24,
    color: "#2e7d32",
    eyeColor: "#e91e63",
    xp: 8,
    behavior: "tank",
  },
  werewolf: {
    id: "werewolf",
    name: "Midnight Werewolf (Boss)",
    hp: 450,
    speed: 85,
    damage: 35,
    size: 32,
    color: "#37474f",
    eyeColor: "#ff1744",
    xp: 50,
    isBoss: true,
    behavior: "charge",
  },
};
