export type ChampionRole = 'marksman' | 'fighter' | 'mage' | 'support' | 'assassin' | 'tank';

export interface ChampionDef {
    id: string;
    name: string;
    greek: string;
    domain: string;
    role: ChampionRole;
    color: number;
    glyph: string;
    blurb: string;
    unlockGlory: number;
    click: number;
    idle: number;
    gold: number;
    crit: number;
}

export const CHAMPIONS: ChampionDef[] = [
    {
        id: 'david',
        name: 'David',
        greek: 'Apollo',
        domain: 'Sun-bow, psalm, kingship',
        role: 'marksman',
        color: 0xe2c36b,
        glyph: 'D',
        blurb: 'The shepherd-king looses a solar arrow down the lane.',
        unlockGlory: 0,
        click: 1.25,
        idle: 1.05,
        gold: 1.0,
        crit: 1.15,
    },
    {
        id: 'samson',
        name: 'Samson',
        greek: 'Heracles',
        domain: 'Pillars, lion, raw strength',
        role: 'fighter',
        color: 0xc47a3a,
        glyph: 'Σ',
        blurb: 'Every tap is a pillar coming down on the tower.',
        unlockGlory: 6,
        click: 1.4,
        idle: 1.1,
        gold: 0.95,
        crit: 1.05,
    },
    {
        id: 'deborah',
        name: 'Deborah',
        greek: 'Athena',
        domain: 'Counsel, palm, war-wisdom',
        role: 'mage',
        color: 0x8fb4d4,
        glyph: 'B',
        blurb: 'She judges the wave before it arrives.',
        unlockGlory: 8,
        click: 1.1,
        idle: 1.25,
        gold: 1.05,
        crit: 1.1,
    },
    {
        id: 'moses',
        name: 'Moses',
        greek: 'Zeus',
        domain: 'Law, mountain, thunder',
        role: 'mage',
        color: 0xf4e7c8,
        glyph: 'Μ',
        blurb: 'Keraunos from the ridge. The lane splits like a sea.',
        unlockGlory: 12,
        click: 1.2,
        idle: 1.2,
        gold: 1.0,
        crit: 1.2,
    },
    {
        id: 'esther',
        name: 'Esther',
        greek: 'Hera',
        domain: 'Scepter, feast, queen-ward',
        role: 'support',
        color: 0xb56b9a,
        glyph: 'Ε',
        blurb: 'Aegis over the nexus. The house does not fall.',
        unlockGlory: 10,
        click: 1.0,
        idle: 1.15,
        gold: 1.2,
        crit: 1.0,
    },
    {
        id: 'jonah',
        name: 'Jonah',
        greek: 'Poseidon',
        domain: 'Storm, whale, reluctant tide',
        role: 'mage',
        color: 0x2a6f8f,
        glyph: 'Ι',
        blurb: 'Trident and deep. Minions drown on the way in.',
        unlockGlory: 14,
        click: 1.15,
        idle: 1.2,
        gold: 1.1,
        crit: 1.05,
    },
    {
        id: 'elijah',
        name: 'Elijah',
        greek: 'Helios',
        domain: 'Fire-chariot, Carmel, drought',
        role: 'mage',
        color: 0xe07040,
        glyph: 'Η',
        blurb: 'The sky answers in flame. Towers blister.',
        unlockGlory: 16,
        click: 1.3,
        idle: 1.15,
        gold: 0.95,
        crit: 1.25,
    },
    {
        id: 'ruth',
        name: 'Ruth',
        greek: 'Demeter',
        domain: 'Gleaning, barley, loyalty',
        role: 'support',
        color: 0x7a9e4a,
        glyph: 'Ρ',
        blurb: 'Every last-hit is a gleaned sheaf of gold.',
        unlockGlory: 9,
        click: 1.0,
        idle: 1.1,
        gold: 1.45,
        crit: 1.0,
    },
    {
        id: 'daniel',
        name: 'Daniel',
        greek: 'Hermes',
        domain: 'Lions, dreams, message',
        role: 'assassin',
        color: 0x4aa39a,
        glyph: 'N',
        blurb: 'Caduceus in the den. He walks between teeth.',
        unlockGlory: 18,
        click: 1.35,
        idle: 1.05,
        gold: 1.05,
        crit: 1.3,
    },
    {
        id: 'gideon',
        name: 'Gideon',
        greek: 'Ares',
        domain: 'Torch, jar, three hundred',
        role: 'fighter',
        color: 0xa33b3b,
        glyph: 'Γ',
        blurb: 'Few against many. The wave breaks on his name.',
        unlockGlory: 15,
        click: 1.2,
        idle: 1.3,
        gold: 1.0,
        crit: 1.1,
    },
    {
        id: 'judith',
        name: 'Judith',
        greek: 'Nike',
        domain: 'Victory, tent, precision',
        role: 'assassin',
        color: 0xefe6d4,
        glyph: 'Θ',
        blurb: 'One clean strike. The lane is already won.',
        unlockGlory: 20,
        click: 1.45,
        idle: 1.0,
        gold: 1.0,
        crit: 1.35,
    },
    {
        id: 'noah',
        name: 'Noah',
        greek: 'Oceanus',
        domain: 'Ark, flood, endurance',
        role: 'tank',
        color: 0x1f4f6b,
        glyph: 'Ν',
        blurb: 'The hull holds. Towers take the sea and remain.',
        unlockGlory: 11,
        click: 0.95,
        idle: 1.2,
        gold: 1.1,
        crit: 0.95,
    },
    {
        id: 'solomon',
        name: 'Solomon',
        greek: 'Apollo Musagetes',
        domain: 'Temple, proverb, measure',
        role: 'mage',
        color: 0xc9a0dc,
        glyph: 'Σ',
        blurb: 'He builds the lane the way he built the house.',
        unlockGlory: 22,
        click: 1.1,
        idle: 1.35,
        gold: 1.15,
        crit: 1.1,
    },
    {
        id: 'jael',
        name: 'Jael',
        greek: 'Artemis',
        domain: 'Hunt, peg, night-camp',
        role: 'marksman',
        color: 0xc8d4dc,
        glyph: 'Ι',
        blurb: 'Moonlit last-hits. The peg always finds the temple.',
        unlockGlory: 17,
        click: 1.3,
        idle: 1.05,
        gold: 1.15,
        crit: 1.4,
    },
    {
        id: 'joshua',
        name: 'Joshua',
        greek: 'Athena Promachos',
        domain: 'Horn, wall, crossing',
        role: 'fighter',
        color: 0x8a9a4a,
        glyph: 'Ι',
        blurb: 'Seven circuits and the tower comes down.',
        unlockGlory: 19,
        click: 1.15,
        idle: 1.25,
        gold: 1.0,
        crit: 1.15,
    },
    {
        id: 'magdalene',
        name: 'Magdalene',
        greek: 'Persephone',
        domain: 'Garden, dawn, return',
        role: 'mage',
        color: 0xd98ba0,
        glyph: 'Μ',
        blurb: 'What dies in the lane comes back as spring.',
        unlockGlory: 24,
        click: 1.2,
        idle: 1.2,
        gold: 1.2,
        crit: 1.2,
    },
];

export const CHAMPION_BY_ID: Record<string, ChampionDef> = Object.fromEntries(
    CHAMPIONS.map((champion) => [champion.id, champion]),
);

export function championById(id: string): ChampionDef {
    return CHAMPION_BY_ID[id] ?? CHAMPIONS[0];
}
