export const DEFAULT_VERBS = [
  "sneak",
  "bribe",
  "fight",
  "talk",
  "craft",
  "hack",
  "drive",
  "investigate",
  "heal",
  "steal",
  "build",
  "cook",
  "pray",
  "barter",
  "climb",
  "dive",
  "radio",
  "farm",
  "pilot",
  "perform",
];

export const LOCATIONS = [
  "A customs office that floods to the knees at high tide",
  "The last dry pew in a church used as a barracks",
  "A kitchen that is also the town's only clinic",
  "A tram car stuck between stations, lights on a timer",
  "The back room of a pawn shop that buys memories",
  "A greenhouse built inside a wrecked dropship",
  "The elevator of a hotel that no longer admits the living to the upper floors",
  "A quarry where the workers have started naming the stones",
  "A radio booth still broadcasting a weather report from last winter",
  "The school gym, night of the ceasefire dance",
  "A dry dock where two crews claim the same hull",
  "The waiting room of a licensed dream clinic",
  "A bridge checkpoint that only opens for funerals",
  "The cellar under the winning tavern",
  "A rooftop apiary above a surveillance market",
  "The chapel of a submarine that cannot surface",
  "A library whose fines are paid in secrets",
  "The last working laundromat in a condemned arcology",
  "A hunting lodge that now processes refugees",
  "The projection booth of a cinema that shows only one film",
  "A ferry cafeteria during a fog delay",
  "The office of a saint who does paperwork",
  "A greenhouse alley between two rival bakeries",
  "The locker room of a mecha hangar after a loss",
  "A tide pool used as a dead drop",
  "The choir loft above a courtroom",
  "A motel ice machine that dispenses ration chips",
  "The border of two farms that share one well",
  "A clocktower workshop where time is sold by the hour",
  "The cargo hold of a ship that is legally a person",
];

export const PRESSURES = [
  "The shift change in eight minutes",
  "The tide is already in the hallway",
  "Someone they love is on the other radio channel",
  "The license expires at sundown",
  "A witness is taking notes, not shots",
  "The last of the medicine is visible in the glass",
  "The crowd will cheer the wrong person if you wait",
  "The power cut is scheduled and posted on the door",
  "A debt collector arrives when the song ends",
  "The child will repeat whatever they hear next",
  "The storm makes the map a liar",
  "The boss is listening through a cheap wall",
  "Rations are counted in front of you",
  "The only key is in a pocket that is currently praying",
  "Curfew is a person, not a siren",
  "The contract auto-signs if nobody speaks",
  "Smoke means the archives are already burning",
  "The duel is legal only until the bell",
  "Your face is on a poster with the wrong name",
  "The patient will wake up mid-sentence",
  "A festival mask makes everyone trustworthy and no one identifiable",
  "The well will be poisoned at noon unless a name is given",
  "Your inventory is full of someone else's problem",
  "The translator is drunk and honest",
  "The camera battery dies on the important frame",
];

export const COMPLICATIONS = [
  "Your usual contact is being audited on the other side of the glass",
  "The verb you prefer is illegal in this room",
  "Success here notifies the wrong faction",
  "The objective is in the next room; this scene is why they don't go",
  "Everyone here is telling the truth; none of it helps",
  "The resource you need is owned by someone you already helped",
  "A skill check that 'fails' is the only moral option",
  "The map is correct and the locals are not",
  "You are overleveled; the obstacle is etiquette",
  "Helping requires using a system the story has called monstrous",
  "The reward was already promised to two other people",
  "An ally will remember the tactic you use, not the result",
  "The door opens; what comes through is a conversation",
  "Time of day is the antagonist",
  "The monster is right; the town is wrong",
  "Someone is filming this for a sermon",
  "The item you came for is in use as a child's toy",
  "A ritual is already halfway complete and stopping it is also violence",
  "Your reputation arrives three minutes before you do",
  "The only witness is a dog, a camera, or a saint — pick later",
  "The lock is easy; the alarm is social",
  "You can save the body or the evidence, not both",
  "A tutorial NPC is here and they are humiliating you on purpose",
  "The weather report is a coded kill list",
  "Paying the tax makes you visible to a kinder enemy",
];

export const NPCS = [
  "A junior clerk who wants to be seen doing this by the book",
  "A cook who used to command the checkpoint",
  "A child translating for adults who should know better",
  "A priest who sells weather",
  "An ex-partner who still has your tools",
  "A medic who bills by the confession",
  "A union steward with a broken radio and a perfect memory",
  "A smuggler who only moves lost animals",
  "A night janitor who owns the building's rumors",
  "A retired duelist grading papers",
  "A saint's intern with a stamp and no authority",
  "A captain who has not told the crew they are already dead on paper",
  "A florist who arranges alibis",
  "The person whose name is on your wanted poster, incorrectly",
  "A choir soloist who hears through walls",
  "A dockworker paid to forget faces and failing at it",
  "A teacher holding the last working textbook as a hostage",
  "A bartender who is also the census",
  "A hacker whose virus is a hymn",
  "A farmer who named the well after an enemy",
  "A midwife who knows which houses still have extra names",
  "A critic livestreaming the raid as cuisine",
  "A quartermaster who loves the inventory more than the people",
  "An actor hired to play the missing official",
  "A guide who gets lost on purpose when the pay is wrong",
];

export const SENSORY = [
  "Wet wool, stamp ink, a radio playing a hymn",
  "Bleach, oranges, a fan that clicks on the same syllable",
  "Gun oil and pastry sugar in the same breath",
  "Salt on the floorboards, a clock that skips a second",
  "Candle smoke, wet chalk, someone counting under their breath",
  "Diesel, lilies, a fluorescent light that hates faces",
  "Copper coins too warm from a pocket",
  "Rain on corrugated iron, soup, a mosquito zapper",
  "Old velvet seats and a fuse box ticking",
  "Machine coolant and cheap coffee",
  "Dust motes in a projector beam, chewed pencils",
  "Iodine, floor wax, a lullaby through a wall",
  "Hot tar, gulls, a tannoy that lies about delays",
  "Yeast, engine grease, a leaking accordion",
  "Snow melt in boots, typewriter ribbon, garlic",
  "Incense covering the smell of a server room",
  "Fish markets at 4 a.m., fluorescent saints",
  "A piano with two dead keys used as a code",
  "Sun through dirty glass, insect drone, photocopy heat",
  "The particular silence after a generator dies",
];

export const CONSTRAINTS = [
  "The NPC is telling the truth. The player cannot afford to believe it.",
  "Remove combat from this scene. Keep the danger.",
  "The objective is in the next room. The scene is why they don't go.",
  "Give the player too much information, all of it from a liar.",
  "The resource they need is owned by someone they already helped.",
  "Make the map smaller. Put two factions in the same corridor.",
  "The player's favorite verb is illegal here.",
  "Start after the fight.",
  "The reward is a relationship that will betray them in twenty minutes of play.",
  "Someone is watching. They take notes, not shots.",
  "The tutorial is a humiliation.",
  "Cut the prologue. Open on a debt.",
  "The monster is right. The town is wrong.",
  "One inventory slot is already full of someone else's problem.",
  "Time of day is the antagonist.",
  "Dialogue cannot name the plot. Only the weather, the food, the debt.",
  "The player is overleveled. The obstacle is etiquette.",
  "Fail the skill check on purpose in the fiction. Succeed in the system. Sit with that.",
  "No new locations. Reuse a room the player already thinks they understand.",
  "The quest-giver wants the player to fail a little, for love or for politics.",
  "Put the cutscene information on a receipt, a hymn board, or a wanted poster.",
  "A child is present. Nobody can use their real verbs until the child leaves.",
  "Success notifies a kinder enemy than failure would have.",
  "The player may take the object or the truth, not both in this scene.",
  "Write it in second person. Then strip every adjective that is not tactile.",
  "The door is unlocked. Leaving is the moral problem.",
  "Give the antagonist a job the town actually needs.",
  "The timer is social: a song, a prayer, a shift whistle.",
  "Let the player use a verb the UI has not named yet. Name it after they do it.",
  "An ally will copy the tactic, not the intention.",
  "Make the reward a schedule: who now expects them weekly.",
  "The scene must work if the player says nothing.",
  "Replace a boss with a form that must be signed.",
  "The map marker is wrong on purpose. A person benefits.",
  "Put the lore on a tool: a blade, a recipe, a key that only fits a throat or a lock.",
  "Two timers, one of them is kindness.",
  "The player already did the violence offscreen. This is the paperwork.",
  "A festival makes everyone kind and nobody identifiable.",
  "The only safe verb is one they hate.",
  "Write the scene so a speedrunner and a roleplayer both have a reason to stay.",
];

export const ANTI_MOVES = [
  "Do not add a continent.",
  "Do not rename the protagonist.",
  "Do not open a new engine project.",
  "Do not wait for the ending.",
  "Do not write a glossary.",
  "Do not design a skill tree to avoid the scene.",
  "Do not invent a new magic system in this session.",
  "Do not start with the creation myth.",
  "Do not polish the first sentence.",
  "Do not ask the internet if the idea is original.",
];
