import type { Protocol, ProtocolId } from "../types";

export const PROTOCOLS: Protocol[] = [
  {
    id: "first-pressure",
    name: "First Pressure",
    forBlock: "blank",
    durationMin: 12,
    promise: "Leave with eight ugly lines of play, a taxed verb, and a problem the player now owns.",
    steps: [
      {
        id: "sensation",
        title: "Name the sensation of play",
        seconds: 60,
        prompt:
          "In one sentence, what does a good session feel like to play — not the plot, the sensation? Example: “I am a thief whose next idea is always worse.”",
        why: "Plot is a rumor. Fantasy of play is a compass. If you cannot feel the session, you cannot write a beat.",
        placeholder: "A good session feels like…",
        stuckHint: "Steal a sport, a job, or a vice. “Chess with a time bomb.” “Catering a funeral.” “Lying to a machine that loves you.”",
      },
      {
        id: "public-lie",
        title: "The world's public lie",
        seconds: 90,
        prompt:
          "What does this place tell children is true? One sentence. It should be useful to someone in power.",
        why: "A world that believes nothing cannot pressure a player. The lie is the first antagonist you can write today.",
        placeholder: "They say that…",
        stuckHint: "Make it almost kind. “Nobody starves who works.” “The sea returns what it takes.” “The dead are off the books.”",
      },
      {
        id: "who-bleeds",
        title: "Who is already bleeding from that lie",
        seconds: 60,
        prompt:
          "Name one person, profession, or creature paying for the lie this week — not in history, this week.",
        why: "Scale is the enemy of a first scene. A week is writeable. A dynasty is a stall.",
        placeholder: "This week, the lie costs…",
        stuckHint: "Pick a job you can see: clerk, cook, night guard, midwife, radio voice, child translator.",
      },
      {
        id: "taxed-verb",
        title: "Tax one verb",
        seconds: 90,
        prompt:
          "Name the first verb the player uses, and why that verb is expensive today. Cost can be social, legal, spiritual, or inventory — not only hit points.",
        why: "A scene is a verb under pressure. If the verb is free, you are writing a cutscene.",
        placeholder: "They must ______, but today that costs ______.",
        stuckHint: "If you have no combat, tax talk. If you have only combat, tax etiquette. If you have stealth, make silence a kind of theft.",
      },
      {
        id: "four-facts",
        title: "Four facts in the room",
        seconds: 90,
        prompt:
          "Using the Forced Hand location (or a room you already have), write four facts: one you can smell, one you can steal, one that can watch you, one that will change in ten minutes.",
        why: "Abstract worlds do not yield sentences. Tactile rooms do. The fourth fact is a clock.",
        placeholder: "Smell / steal / watch / change…",
        stuckHint: "If the room is empty, it is not a room. Add a receipt, a wet coat, a radio, a sleeping animal.",
      },
      {
        id: "ugly-eight",
        title: "Ugly eight lines",
        seconds: 240,
        prompt:
          "Write eight lines in second person present (“You…”). No backstory. They walk in, the verb is costly, someone wants something. Bad prose is the assignment.",
        why: "You are not producing literature. You are producing a playable draft you can extract systems from.",
        placeholder: "You step into…",
        stuckHint: "Start with the body: boots, hands, breath. If you stall on line three, write “You do the wrong verb anyway.”",
      },
      {
        id: "extract-system",
        title: "Extract one system",
        seconds: 60,
        prompt:
          "If this scene had to be true every time the player entered, what would the game need? One meter, rule, UI tell, or NPC schedule. Not five.",
        why: "Narrative that cannot survive a second playthrough is a cutscene. A system makes the beat replayable.",
        placeholder: "The game would need…",
        stuckHint: "A reputation flag, a tide clock, a limited bribe item, a witness meter, a locked verb until a debt is paid.",
      },
      {
        id: "exit-hook",
        title: "The problem they now own",
        seconds: 60,
        prompt:
          "End the beat with a problem that follows the player out of the room. Not a quest marker — a person, a timer, or an inventory fact.",
        why: "Middles write themselves when the player is already in trouble. Do not send them home clean.",
        placeholder: "They leave with…",
        stuckHint: "A name they said aloud. A stamp on a paper. A child who saw the verb. A radio that stays on.",
      },
    ],
  },
  {
    id: "iceberg-cut",
    name: "Iceberg Cut",
    forBlock: "lore",
    durationMin: 12,
    promise: "One player-facing shard, the buried truth, the cost of knowing, and a scene that puts the shard in the way of a verb.",
    steps: [
      {
        id: "five-loves",
        title: "Five facts you love",
        seconds: 90,
        prompt: "List five lore facts you are proud of. Do not expand them. Fragments are legal.",
        why: "You need a menu before you can cut. Pride is data: it shows what you are protecting from play.",
        placeholder: "1.\n2.\n3.\n4.\n5.",
        stuckHint: "Names, wars, gods, materials, taboos. If you have fifty, pick the five you would tattoo on a prop.",
      },
      {
        id: "bumpable",
        title: "One bumpable fact",
        seconds: 60,
        prompt:
          "Which one can a player physically bump into this session — graffiti, a tool, a body, a form, a hymn, a smell?",
        why: "If it cannot occupy space, it is not in the game yet. It is in a wiki.",
        placeholder: "This session they can bump into…",
        stuckHint: "Put it on an object that already exists in your greybox: a door, a cup, a corpse, a ticket.",
      },
      {
        id: "shard",
        title: "The player-facing shard",
        seconds: 90,
        prompt:
          "Write the one line the player actually gets: UI, graffiti, rumor, item description. It should be incomplete on purpose.",
        why: "Players build the iceberg from shards. Complete lectures kill curiosity.",
        placeholder: "They read / hear / see: “…”",
        stuckHint: "Cut the explanation. Keep the attitude. “We don't bury them on Tuesdays.” is better than a calendar of rites.",
      },
      {
        id: "truth",
        title: "The true thing underneath",
        seconds: 60,
        prompt: "Write the truth they may never learn. One or two sentences. This is for you, not the journal.",
        why: "You need a private compass so the shard does not drift. The player does not need the compass.",
        placeholder: "The truth is…",
        stuckHint: "Make the truth worse and more human than the myth. Institutions, not demons, if you can.",
      },
      {
        id: "cost-of-knowing",
        title: "Cost of knowing",
        seconds: 90,
        prompt:
          "What does a character pay if they learn the truth — status, safety, a relationship, a verb they can no longer use?",
        why: "Information without cost is flavor text. Cost makes investigation a game.",
        placeholder: "If they know, they lose / become / can no longer…",
        stuckHint: "They can no longer pray, trade in this district, or look their quest-giver in the eye.",
      },
      {
        id: "shard-in-the-way",
        title: "Shard in the way of a verb",
        seconds: 180,
        prompt:
          "Write a short scene where the shard blocks or taxes a verb. They came to sneak / bribe / heal / loot. The lore is in the way, not in a cutscene.",
        why: "This is the conversion of bible into level design.",
        placeholder: "You came here to… but…",
        stuckHint: "The hymn board is the lock. The rumor is the password. The smell is the alarm.",
      },
      {
        id: "cut-list",
        title: "Cut list",
        seconds: 90,
        prompt:
          "Name three loved facts that leave the playable GDD for now. You are not deleting them. You are refusing to stall on them.",
        why: "Permission to not use material is the actual skill. Block often is loyalty to unused notes.",
        placeholder: "Not this month:\n-\n-\n-",
        stuckHint: "If it needs a map, a language, or a bloodline chart, it goes on this list.",
      },
    ],
  },
  {
    id: "verb-tax",
    name: "Verb Tax",
    forBlock: "ludo",
    durationMin: 12,
    promise: "A verb you already have becomes expensive for a human reason, collected by a person, visible in feedback.",
    steps: [
      {
        id: "verb-list",
        title: "Verbs in the build",
        seconds: 60,
        prompt:
          "List the verbs the player can actually do in the current build or greybox. Not the fantasy list — the real one.",
        why: "Fiction that ignores the build will always feel glued on. Honesty about verbs is the patch.",
        placeholder: "They can…",
        stuckHint: "Walk, shoot, talk, cook, pause. Include the embarrassing ones. Pause is a verb if you write it.",
      },
      {
        id: "neglected-verb",
        title: "The neglected verb",
        seconds: 60,
        prompt: "Which verb has never appeared in a quest text, bark, or cutscene? Circle it. That is today's protagonist.",
        why: "The neglected verb is where the game is already more interesting than the script.",
        placeholder: "The ignored verb is…",
        stuckHint: "If they can crouch, loot, reload, or whistle, and the story never notices, start there.",
      },
      {
        id: "human-cost",
        title: "Make it expensive for a human reason",
        seconds: 120,
        prompt:
          "Why is that verb costly today for a person, not a balance spreadsheet? Law, etiquette, love, faith, noise, witnesses.",
        why: "A cooldown is not a story. A person who will remember is.",
        placeholder: "Today, doing this means…",
        stuckHint: "It wakes the baby. It voids the truce. It is how the last regime found people. It is rude in this kitchen.",
      },
      {
        id: "tax-collector",
        title: "Who collects the tax",
        seconds: 90,
        prompt: "Name the person (or institution with a face) who notices. What do they want from the player noticing?",
        why: "Systems become drama when someone benefits from the rule.",
        placeholder: "They notice because they want…",
        stuckHint: "A clerk, a choir, a rival thief, a saint's intern, the person whose job is to pretend they didn't see.",
      },
      {
        id: "change",
        title: "What paying or dodging changes",
        seconds: 90,
        prompt:
          "Write two outcomes: they pay the tax, they dodge it. Each must change a relationship, flag, or access — not only money.",
        why: "If both paths return to the same hallway with the same NPCs, you did not write a choice.",
        placeholder: "Pay →\nDodge →",
        stuckHint: "Access to a room, a name used later, an ally who copies the tactic, a faction that now owes a kindness.",
      },
      {
        id: "tax-scene",
        title: "Write the collection scene",
        seconds: 210,
        prompt: "Ugly draft. The player tries the neglected verb. The collector arrives before the combat music would have.",
        why: "You are proving the tax can be staged, not just argued in a GDD.",
        placeholder: "You try to…",
        stuckHint: "Keep weapons holstered. If you reach for a health bar, you are escaping the assignment.",
      },
      {
        id: "feedback",
        title: "Make the cost visible",
        seconds: 60,
        prompt:
          "How does UI or the world react — a glance, a meter, a stamp, a bark, a locked door tomorrow? One tell.",
        why: "Invisible story costs train the player to ignore story. Visible costs train them to play it.",
        placeholder: "The tell is…",
        stuckHint: "A reputation pip, a wet footprint, a receipt, the NPC using a different greeting set.",
      },
    ],
  },
  {
    id: "mouth-obstacle",
    name: "Mouth with an Obstacle",
    forBlock: "dialogue",
    durationMin: 12,
    promise: "Six lines of speech that are tactics, plus player replies that are verbs, not moods.",
    steps: [
      {
        id: "want-30",
        title: "Want in thirty seconds",
        seconds: 60,
        prompt: "What does this speaker want the player to do or say in the next thirty seconds? Concrete. Not “trust.”",
        why: "Dialogue without a want is a README. Characters do not chat; they work.",
        placeholder: "They want you to…",
        stuckHint: "Leave. Sign. Lie to the person behind you. Put the gun down. Say a name. Taste the soup.",
      },
      {
        id: "first-tactic",
        title: "First tactic",
        seconds: 60,
        prompt: "How do they try — flattery, procedure, joke, threat, helplessness, expertise, seduction, silence?",
        why: "Voice is tactic, not vocabulary. Two clerks can share a dialect and still play different games.",
        placeholder: "They try…",
        stuckHint: "If you don't know, give them paperwork. Procedure is a rich tactic.",
      },
      {
        id: "cannot-say",
        title: "Why they cannot say it plainly",
        seconds: 90,
        prompt:
          "What makes honesty expensive — a listener, a law, a love, a wire, a god, shame? Name the obstacle in the room.",
        why: "Subtext is not decoration. It is the second game inside the conversation.",
        placeholder: "They cannot say it because…",
        stuckHint: "A child is present. A camera. A translator. A vow. The player is the wrong class to hear it.",
      },
      {
        id: "interruption",
        title: "The interruption",
        seconds: 60,
        prompt:
          "What hits mid-line — another NPC, a system ping, weather, a body, a timer? The world must refuse to be a talk show.",
        why: "Games are bad at talk shows and good at interruption. Use the engine.",
        placeholder: "Mid-sentence…",
        stuckHint: "The tide. The tannoy. The baby. The reload. The guard's radio. The soup boiling over.",
      },
      {
        id: "six-lines",
        title: "Six lines, no plot names",
        seconds: 210,
        prompt:
          "Write six lines. Ban the name of the MacGuffin, the war, and the prophecy. They may talk about weather, food, debt, the interruption.",
        why: "Exposition with quotation marks is the usual failure. Ban the nouns and the want still leaks.",
        placeholder: "NPC:\nYou:\nNPC:\n…",
        stuckHint: "If a line could be a journal entry, cut it. If a line could be said while stirring a pot, keep it.",
      },
      {
        id: "subtext-pass",
        title: "Subtext pass",
        seconds: 90,
        prompt:
          "Under each NPC line, in brackets, write what they mean. Then delete any spoken line that already says the bracket.",
        why: "If speech and subtext match, you wrote a lecture. Mismatch is playable.",
        placeholder: "Line\n[means]",
        stuckHint: "The bracket should embarrass them if read aloud in court.",
      },
      {
        id: "player-replies",
        title: "Replies that are tactics",
        seconds: 90,
        prompt:
          "Write three player options as tactics, not moods. Not “Be kind / Be rude / Ask more.” Name the verb: cover for them, report them, change the subject, pay, walk.",
        why: "Mood wheels produce wallpaper. Tactics produce branches you can flag.",
        placeholder: "1.\n2.\n3.",
        stuckHint: "Each option should make a different person in the room safer.",
      },
    ],
  },
  {
    id: "reversal-beat",
    name: "The Reversal Beat",
    forBlock: "middle",
    durationMin: 11,
    promise: "The tactic the player was trained to trust still works — and makes a worse problem.",
    steps: [
      {
        id: "trained-tactic",
        title: "What they were trained to trust",
        seconds: 60,
        prompt:
          "What tactic has the game rewarded so far — stealth, violence, charity, hacking, cooking, talking down? Name it bluntly.",
        why: "A middle needs a broken training loop, not a new map.",
        placeholder: "They have learned that… works.",
        stuckHint: "Look at your first two hours. Whatever they spammed is the tactic.",
      },
      {
        id: "works-worse",
        title: "It works, and it worsens",
        seconds: 240,
        prompt:
          "Write the scene where the tactic still succeeds on its own terms (the lock opens, the enemy drops, the crowd loves you) and the world gets worse because of that success.",
        why: "Failure is cheap drama. Tragic success is a middle. The player does not feel cheated; they feel implicated.",
        placeholder: "You do the thing that always works…",
        stuckHint: "The rescued person is the witness. The opened door floods the lower ward. The confession you extracted is already a sermon.",
      },
      {
        id: "new-pressure",
        title: "The pressure that replaces it",
        seconds: 90,
        prompt: "Name the new clock, debt, or watcher that did not exist before the “win.”",
        why: "Without a replacement pressure, the middle sags again in two pages.",
        placeholder: "Now they have to live with…",
        stuckHint: "A schedule. A child. A broadcast. A stamp. A faction that now calls you family.",
      },
      {
        id: "crosshairs",
        title: "Debt or crosshairs",
        seconds: 90,
        prompt: "Who is now in the player's debt, or who now has the player in their crosshairs? Give them a face and a next Ask.",
        why: "Middles are social. Bosses can wait.",
        placeholder: "They owe / they hunt because…",
        stuckHint: "The person you saved wants a second favor that is worse. The person you beat wants to hire you.",
      },
      {
        id: "next-verb",
        title: "The next verb",
        seconds: 90,
        prompt:
          "What verb must they learn, or reuse wrongly, because of this beat? One. This is the design handoff to systems and levels.",
        why: "A reversal that does not teach a new toy is just a cutscene with guilt.",
        placeholder: "They will have to…",
        stuckHint: "Negotiate with someone they robbed. Heal an enemy. Return an item. Walk in daylight. Cook for a funeral.",
      },
      {
        id: "act-image",
        title: "Image that ends the act",
        seconds: 90,
        prompt: "One image, no speech. The player can still move. What do they see as the music would change?",
        why: "Act breaks in games are remembered as spaces, not speeches.",
        placeholder: "They look at…",
        stuckHint: "A table set for more people than are alive. A dry river. A wanted poster with a kind photo. Lights coming on in the wrong district.",
      },
    ],
  },
  {
    id: "three-beat-spine",
    name: "Three-Beat Spine",
    forBlock: "quest",
    durationMin: 12,
    promise: "A mission that is three playable beats, a twist that changes the want, and a reward that is a problem.",
    steps: [
      {
        id: "objective-8",
        title: "Objective in eight words",
        seconds: 60,
        prompt:
          "Write the objective in eight words or fewer. Ban “collect” unless the thing collected is a person or a relationship.",
        why: "If you need a paragraph, you have a campaign, not a quest. Compression finds the verb.",
        placeholder: "Get / stop / return / hide / name…",
        stuckHint: "Bring the choir home. Stop the form being signed. Return the well's name.",
      },
      {
        id: "why-now",
        title: "Why now",
        seconds: 60,
        prompt: "What clock makes this this week, not someday? Tide, trial, wedding, rust, a child, a shift, a broadcast.",
        why: "Without why-now, the player is right to go fishing.",
        placeholder: "If they wait…",
        stuckHint: "Someone else will do it badly. The license expires. The river rises. The saint arrives.",
      },
      {
        id: "why-you",
        title: "Why this player",
        seconds: 90,
        prompt:
          "Why not a nameless adventurer? Use a fact already true of this character or their mess — a skill, a debt, a face, a crime.",
        why: "Generic heroes produce generic fetch. Specific debt produces play.",
        placeholder: "It has to be them because…",
        stuckHint: "They still have the key. They owe the cook. They look like the missing official. They are the only one the dog allows.",
      },
      {
        id: "beat-1",
        title: "Beat 1 — known verb",
        seconds: 90,
        prompt: "The first door they can open with a verb they already have. Where, who, what success looks like.",
        why: "Teach competence before you tax it. The player should feel they know how to begin.",
        placeholder: "They use ______ at ______ and get…",
        stuckHint: "A conversation, a lock they understand, a bribe with a known currency.",
      },
      {
        id: "beat-2",
        title: "Beat 2 — tax a second system",
        seconds: 90,
        prompt:
          "Complication that needs a second verb or resource. Do not add a new map if you can add a new social rule in the same space.",
        why: "Padding is travel. Design is a second pressure in a known space.",
        placeholder: "Then they must also…",
        stuckHint: "The key works; the witness does not leave. The fight is easy; the camera is on.",
      },
      {
        id: "beat-3",
        title: "Beat 3 — success changes the want",
        seconds: 90,
        prompt:
          "The twist: they can still succeed, but what they wanted is no longer what success means. Name both.",
        why: "A twist that only denies the objective is a slap. A twist that upgrades the want is a story.",
        placeholder: "They came for ______. They leave needing ______.",
        stuckHint: "They came for medicine and leave with a name. They came to stop a duel and become its witness of record.",
      },
      {
        id: "reward-problem",
        title: "Reward that is a problem",
        seconds: 90,
        prompt: "What do they get that will bother them in twenty minutes of play? Access, a person, a schedule, an object with a rule.",
        why: "Gold is a receipt. A problem is a sequel.",
        placeholder: "They get… which means…",
        stuckHint: "A radio that stays on. A child. A badge. A seat at a table. A debt in their inventory.",
      },
      {
        id: "fail-forward",
        title: "Fail-forward",
        seconds: 90,
        prompt:
          "If they skip, fail, or sell the objective, what still changes in the world? One flag. Do not pause the campaign.",
        why: "Quests that require success are novels. Games need the world to keep moving.",
        placeholder: "If they fail…",
        stuckHint: "Someone else completes it cruelly. The clock expires in public. The NPC does the verb themselves and hates you for the necessity.",
      },
    ],
  },
  {
    id: "want-need-ask",
    name: "Want / Need / Ask",
    forBlock: "npc",
    durationMin: 12,
    promise: "An NPC with a week, a lie, an Ask, and a verb that cracks them — not a quest dispenser.",
    steps: [
      {
        id: "public-job",
        title: "Public job",
        seconds: 45,
        prompt: "What does the world think this person is for? One line. The vending-machine version.",
        why: "You need the mask before you can crack it. Players meet the job first.",
        placeholder: "They are the…",
        stuckHint: "Quartermaster. Ferryman. Teacher. Saint's intern. Night cook.",
      },
      {
        id: "private-want",
        title: "Private want this week",
        seconds: 60,
        prompt: "What do they want before Sunday? Small enough to fit in a pocket or a conversation.",
        why: "Lifetime goals produce speeches. Weekly wants produce scenes.",
        placeholder: "This week they want…",
        stuckHint: "A signature. A night off. Their name off a list. The good pan back. A lie told to a child.",
      },
      {
        id: "the-lie",
        title: "The lie they must keep believing",
        seconds: 90,
        prompt:
          "What story about themselves or the town must remain intact or they will fall apart? This is the need's enemy.",
        why: "Need is abstract until you know the lie that protects them from it.",
        placeholder: "They need to keep believing that…",
        stuckHint: "That they are still a captain. That the well is clean. That the player is a customer, not family.",
      },
      {
        id: "the-ask",
        title: "The Ask",
        seconds: 90,
        prompt:
          "What will they ask the player to do? It should serve the want and threaten the lie, even if they don't see that.",
        why: "The Ask is the playable interface of a soul. No Ask, no character in a game.",
        placeholder: "They ask you to…",
        stuckHint: "Watch the shop. Sign as someone else. Taste first. Forget a face. Take the child as far as the bridge.",
      },
      {
        id: "withheld",
        title: "What they will not tell",
        seconds: 60,
        prompt: "One withheld fact. The player can discover it with a verb, not a loyalty meter.",
        why: "Secrets that only unlock by grinding affection are television. Secrets in rooms are games.",
        placeholder: "They will not say…",
        stuckHint: "Put it in a drawer, a hymn, a second set of books, a pocket, a rumor the rival tells for free.",
      },
      {
        id: "verb-crack",
        title: "A verb that cracks them",
        seconds: 120,
        prompt:
          "How does play — cook, steal, wait, miss a shot, return an item — reveal the crack, without a confession cutscene?",
        why: "If only dialogue reveals them, they are not in the game's language.",
        placeholder: "If the player ______, the crack shows because…",
        stuckHint: "They flinch when you holster. They undercharge. They set two bowls. They know the back way and hate that you saw it.",
      },
      {
        id: "first-four",
        title: "First four lines plus an action",
        seconds: 180,
        prompt:
          "Write their first four spoken lines and one action beat (hands, eyes, a task they will not drop). Ban a quest summary.",
        why: "You are casting them in a room, not writing their IMDb bio.",
        placeholder: "They are doing ______.\n“…”",
        stuckHint: "Keep them working. A character who only faces the player is a UI panel.",
      },
      {
        id: "help-vs-use",
        title: "Help vs use",
        seconds: 90,
        prompt:
          "How do they change if the player helps the want versus uses the job? Two futures, one sentence each. These are flags, not novels.",
        why: "NPCs feel fake when every path returns the same greeting set.",
        placeholder: "If helped…\nIf used…",
        stuckHint: "Helped: they become a bad ally (too loyal). Used: they do the job perfectly and never look at you.",
      },
    ],
  },
  {
    id: "backward-door",
    name: "Write Backward One Door",
    forBlock: "ending",
    durationMin: 11,
    promise: "Three possible endings stay in a drawer. You write the scene that makes any of them able to land.",
    steps: [
      {
        id: "three-endings",
        title: "Three endings, five words each",
        seconds: 120,
        prompt:
          "Name three possible endings in five words each. Do not pick one. The point is to prove you can hold more than one.",
        why: "Ending-hostage is often fear of choosing. Listing reduces the myth of the One True Finale.",
        placeholder: "A: …\nB: …\nC: …",
        stuckHint: "They stay. They leave. They become the institution. The town burns and is kinder. The lie is kept for a child.",
      },
      {
        id: "shared-truth",
        title: "What must be true of the player",
        seconds: 120,
        prompt:
          "For any of those endings to land, what must already be true of the player — a crime, a bond, a skill, a public stance?",
        why: "Endings fail when they refer to a protagonist the player never got to be. Build that person now.",
        placeholder: "By then they must have…",
        stuckHint: "Been seen. Chosen a table. Used a forbidden verb in public. Saved the wrong person on purpose.",
      },
      {
        id: "not-the-finale",
        title: "The scene that creates that truth",
        seconds: 240,
        prompt:
          "Write that scene. It is not the finale. It is the last door before a finale could exist. Leave more than one ending possible.",
        why: "This is the only page you owe today. The drawer can hold the rest.",
        placeholder: "You…",
        stuckHint: "A public signature. A funeral they cannot skip. A verb used in daylight. A child asking a question they answer.",
      },
      {
        id: "still-open",
        title: "What can still go either way",
        seconds: 90,
        prompt: "After this scene, which fork is still alive? Name it so you do not accidentally lock the hostage ending.",
        why: "Writers often smuggle a chosen ending into the “setup” scene. Catch yourself.",
        placeholder: "Still possible: …",
        stuckHint: "They can still betray the town. They can still keep the lie. They can still leave the weapon on the table.",
      },
      {
        id: "drawer",
        title: "Put the endings in a drawer",
        seconds: 60,
        prompt:
          "Write one sentence: you are allowed to start. The finales stay listed, unchosen. Then name the next playable beat (not the credits).",
        why: "The protocol fails if you immediately reopen the hostage negotiation. Close it on paper.",
        placeholder: "I can start because… Next beat: …",
        stuckHint: "Next beat is a room, a verb, a person. It is not “figure out the ending.”",
      },
    ],
  },
  {
    id: "first-verb-story",
    name: "First Verb is the Story",
    forBlock: "onboard",
    durationMin: 12,
    promise: "A first-three-minutes beat where failure is diegetic, success costs something, and UI copy is in-world.",
    steps: [
      {
        id: "teach-verb",
        title: "The one verb you must teach",
        seconds: 60,
        prompt: "Name the one verb the first three minutes must teach. Not the whole control scheme.",
        why: "Tutorials stall when they teach an encyclopedia. One verb can carry a story.",
        placeholder: "They must learn to…",
        stuckHint: "Aim, crouch, ladle, radio, stamp, dock, lie, plant.",
      },
      {
        id: "fictional-reason",
        title: "Why they do it (not “to learn”)",
        seconds: 90,
        prompt: "Give a fictional reason they perform the verb. Ban “this is the training course” unless the humiliation is the point.",
        why: "Players forgive teaching that is also a situation. They do not forgive a manual with a skybox.",
        placeholder: "In the fiction they are…",
        stuckHint: "Hiding a person. Feeding a queue. Stamping exits. Cutting fruit for a saint. Docking before the patrol.",
      },
      {
        id: "diegetic-fail",
        title: "Diegetic failure",
        seconds: 90,
        prompt:
          "What does failure look like in the world — spilled soup, a stare, a stamp on the wrong paper, a laugh — not a red tooltip?",
        why: "Game-over screens are not onboarding. Social or material failure teaches and characterizes.",
        placeholder: "If they fail…",
        stuckHint: "The NPC does it for them and remembers. The line gets longer. The child repeats the mistake.",
      },
      {
        id: "success-cost",
        title: "Success that costs",
        seconds: 90,
        prompt: "If they succeed, what do they lose or take on — time, dignity, a secret, a debt, the last of something?",
        why: "Free success teaches that the world is a gym. Cost teaches that the world is a place.",
        placeholder: "Success costs…",
        stuckHint: "They are now late. They are now visible. They now owe the cook. They used the last clean stamp.",
      },
      {
        id: "who-watches",
        title: "Who watches them fail",
        seconds: 60,
        prompt: "Name the watcher. Their opinion should matter later, even as a greeting change.",
        why: "An empty tutorial is a void. A watcher turns practice into relationship.",
        placeholder: "Watching: …",
        stuckHint: "A rival. A child. A camera. The person they will have to ask for help in act two.",
      },
      {
        id: "three-minutes",
        title: "Ten-line first three minutes",
        seconds: 240,
        prompt:
          "Beat-by-beat, ten lines, of the first three minutes. Include the verb, the fail, the cost, the watcher. No main menu speech.",
        why: "This is the vertical slice of feeling. If it is boring on paper, it will be boring with VFX.",
        placeholder: "1. You…",
        stuckHint: "Start in motion. They already have dirty hands. The verb is required by a queue of people.",
      },
      {
        id: "ui-line",
        title: "One in-world UI line",
        seconds: 60,
        prompt:
          "Write one prompt, tooltip, or objective line that could exist as a sign, hymn, receipt, or bark. Ban “Press X to…” unless a character says it.",
        why: "UI is voice. Default engine copy is how onboardings die.",
        placeholder: "On screen / on a sign: “…”",
        stuckHint: "“Stamps after the prayer.” “Keep the ladle moving.” “If you can hear the patrol, you are standing wrong.”",
      },
    ],
  },
  {
    id: "kill-the-menu",
    name: "Kill the Menu",
    forBlock: "ideas",
    durationMin: 12,
    promise: "One surviving player-fantasy sentence, stolen organs from the rest, and a first beat instead of a new project.",
    steps: [
      {
        id: "menu",
        title: "The menu (max eight)",
        seconds: 120,
        prompt: "List the competing ideas, maximum eight. One line each. No pitching. No new ninth.",
        why: "You cannot choose among an infinite cloud. A menu is already a kindness.",
        placeholder: "1.\n2.\n3.",
        stuckHint: "If you have more than eight, the extras are flavors, not games. Fold them into a line or let them go.",
      },
      {
        id: "score",
        title: "Score playable-this-month",
        seconds: 90,
        prompt:
          "Score each 0–2 for “playable this month with skills and tools you already have.” Be cruel. Coolness is not a column.",
        why: "Block-as-abundance often hides fear of the small game you could actually ship.",
        placeholder: "1. (score)\n2. (score)",
        stuckHint: "2 means a greybox verb exists. 0 means a new engine, a team, or a PhD.",
      },
      {
        id: "pick-verbs",
        title: "Pick the one with verbs you have",
        seconds: 60,
        prompt:
          "Choose the idea that reuses the most verbs you already have in a prototype, jam, or muscle memory. Write its name. Mourn once.",
        why: "The right game is often the one that does not require becoming a different developer first.",
        placeholder: "I will make…",
        stuckHint: "If two are tied, pick the one you can describe as a sensation of play in one sentence.",
      },
      {
        id: "funeral",
        title: "Funeral theft",
        seconds: 180,
        prompt:
          "For each discarded idea, one sentence: what organ do you steal — a verb, a room, an NPC, a joke, a tax? Then let the idea die.",
        why: "Killing ideas fails when you believe you must keep them intact. Theft lets you commit.",
        placeholder: "From X I steal…",
        stuckHint: "Steal the checkpoint. Steal the soup. Steal the liar. Do not steal the whole map.",
      },
      {
        id: "fantasy-sentence",
        title: "Player fantasy sentence",
        seconds: 90,
        prompt: "Write the surviving game as one sentence of player fantasy. “You are a ___ who ___, but ___.”",
        why: "This is the poster and the test. If you cannot say it, you chose a pile, not a game.",
        placeholder: "You are a … who …, but …",
        stuckHint: "Need a but. The but is the tax. Without a but you have a career simulator nobody asked for.",
      },
      {
        id: "first-beat-now",
        title: "First beat, not a new repo",
        seconds: 180,
        prompt:
          "Write eight “You…” lines of the first playable beat of the surviving idea. You are not allowed to start a new project in this step.",
        why: "The usual escape is a clean folder. Stay in the mess. Produce the beat.",
        placeholder: "You…",
        stuckHint: "Use a Forced Hand if the room is empty. Tax one verb. End with a problem they own.",
      },
    ],
  },
  {
    id: "emergency",
    name: "Emergency Four",
    forBlock: "any",
    durationMin: 4,
    promise: "When you have four minutes: a Forced Hand, eight lines, an exit problem. No diagnosis required.",
    steps: [
      {
        id: "accept-hand",
        title: "Accept the Forced Hand",
        seconds: 45,
        prompt:
          "Read the Forced Hand. Do not reroll more than once. Rewrite it in your own nouns if you must, but keep location, pressure, verb, complication, NPC, sensory.",
        why: "Choice is the disease. A dealt hand is the cure for four minutes of stall.",
        placeholder: "In this room: …",
        stuckHint: "Change only proper names. Keep the taxes.",
      },
      {
        id: "eight-now",
        title: "Eight lines now",
        seconds: 150,
        prompt: "Second person, present. You enter. The verb is costly. The NPC wants something. The clock is running. Ugly is correct.",
        why: "Volume first. You can extract a system later if the lines exist.",
        placeholder: "You…",
        stuckHint: "If line four dies, describe hands. If line six dies, have the NPC interrupt.",
      },
      {
        id: "own-problem",
        title: "They own a problem",
        seconds: 45,
        prompt: "One sentence: what follows them out of the room?",
        why: "A complete emergency session ends in motion, not in a saved blank page.",
        placeholder: "They leave with…",
        stuckHint: "A name, a stain, a receipt, a child, a radio, a missed curfew.",
      },
    ],
  },
];

export function getProtocol(id: ProtocolId): Protocol {
  const found = PROTOCOLS.find((protocol) => protocol.id === id);
  if (!found) {
    throw new Error(`Unknown protocol: ${id}`);
  }
  return found;
}

export function protocolDurationSeconds(protocol: Protocol): number {
  return protocol.steps.reduce((sum, step) => sum + step.seconds, 0);
}
