import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Bakes the content this demo needs into a TypeScript module.
 *
 * The published page has no server to ask, so content must ship inside the
 * bundle. Rather than embed the whole 1,270-item catalogue, this takes the one
 * location and only the items and skills it actually references -- keeping the
 * real imported CC0 names and descriptions, which is the point.
 */
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..', '..', '..');
const generated = path.join(root, 'packages', 'content', 'generated');

const manifest = JSON.parse(await readFile(path.join(generated, 'manifest.json'), 'utf8'));
const locationId = manifest.locations[0];
const location = JSON.parse(
  await readFile(path.join(generated, 'locations', `${locationId}.json`), 'utf8'),
);

const itemIds = new Set<string>();
const skillIds = new Set<string>();
for (const entity of location.entities) {
  if (!entity.yield) continue;
  itemIds.add(entity.yield.item);
  skillIds.add(entity.yield.skill);
}

const items = manifest.items.filter((i: { id: string }) => itemIds.has(i.id));
const skills = manifest.skills.filter((s: { id: string }) => skillIds.has(s.id));

const missing = [...itemIds].filter((id) => !items.some((i: { id: string }) => i.id === id));
if (missing.length > 0) throw new Error(`content missing items: ${missing.join(', ')}`);

const out = `// Generated by scripts/embed-content.ts. Do not edit.
// Sources: ${manifest.sources.join(', ')}
import type { ItemDef, Location, SkillDef } from '@glimmer/shared';

export const CONTENT_SOURCES: string[] = ${JSON.stringify(manifest.sources)};
export const CATALOGUE_SIZE = { items: ${manifest.items.length}, skills: ${manifest.skills.length} };
export const location = ${JSON.stringify(location, null, 2)} as unknown as Location;
export const items: ItemDef[] = ${JSON.stringify(items, null, 2)};
export const skills: SkillDef[] = ${JSON.stringify(skills, null, 2)};
`;

await mkdir(path.join(here, '..', 'src'), { recursive: true });
await writeFile(path.join(here, '..', 'src', 'content.generated.ts'), out);
console.log(
  `embedded ${items.length} items, ${skills.length} skills, location "${location.name}" (sources: ${manifest.sources.join(', ')})`,
);
